// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oveazlyyaixldgvsvbyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZWF6bHl5YWl4bGRndnN2YnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTM5NzQsImV4cCI6MjA2NDg4OTk3NH0.COdfBWRUaBy-h3GZsc8J7epA5OPFU8HN20JRP3zOEcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);